# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 96f7fa0fda40fe4052a297b69a8aa452d6325babdb95356c90f36f3b45db494ddc3238a80b206d604b4c62668f39dba2a6d8c36020d8afaa200fc95f78cbb331

test:
  secret_key_base: bee022281d2c315191de241418f2e4872f0611335f8ddae42a46ec0544ff2e5b4076b52d7b81f7ddc8afe417057bf9ccc1aeb53fb0298a92b466bf32bb367ba2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
